import type { Metadata } from "next";
import "./globals.css";
import { FilterProvider } from "@/context/FilterContext";

export const metadata: Metadata = {
  title: "Densa-task",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                const isDarkMode = localStorage.theme === "dark" || 
                  (!("theme" in localStorage) && window.matchMedia("(prefers-color-scheme: dark)").matches);
                document.documentElement.classList.toggle("dark", isDarkMode);
              })();
            `,
          }}
        />
      </head>
      <body className="antialiased">
        <FilterProvider>{children}</FilterProvider>
      </body>
    </html>
  );
}
